### PR TITLE
Resources added

### PR DESCRIPTION
**Pull request by kelvinparmar**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have `npm run build` and `npm run serve` locally before submitting this PR
- [x] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation

# Summary

### Does this close any open issues?
Closes xx

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by kelvinparmar** [comment]
@yumengwang03 Please check it , Is it  ok ?

**Review by yumengwang03 — CHANGES_REQUESTED** [review]
Can you move this section right before Troubleshooting and have the title as Download Logs for Blueprint Historical Runs? Many thanks!

**Comment by kelvinparmar** [comment]
Yeah sure @yumengwang03

**Comment by kelvinparmar** [comment]
Ohh sorry @yumengwang03 I missed to change this one

**Review by yumengwang03 — APPROVED** [review]
LGTM

**Comment by yumengwang03** [comment]
> Ohh sorry @yumengwang03 I missed to change this one

No problem at all! I just did a quick fix.

**Pull request merged**
