### PR TITLE
docs: Add "Debugging DORA Issue Metrics" section to "Dashboard Troubleshooting" guide

### PR DESCRIPTION
**Pull request by KucherenkoSerhiy**
Co-authored with: Louis.z <louis.s4372121@gmail.com>

docs: Add "Debugging DORA Issue Metrics" section to "Dashboard Troubleshooting" guide. Supplied with .png diagrams for each of the DORA metrics

### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [✔️] I have `npm run build` and `npm run serve` locally before submitting this PR
- [✔️] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation

# Summary

### Does this close any open issues?
-

### Screenshots
-

### Other Information

This PR carries some docs to help debugging DORA charts

### CODE REVIEW

**Review by Startrekzky — CHANGES_REQUESTED** [review]
There need to be several changes:
1. Move the images to `docs/Configure/images`,  we stopped using the static folder for `versioning` reasons
image

2. Add the raw files of the images to docs/Configure/images for later refinement
3. Make a copy of the changes to v0.18 docs
image

**Comment by KucherenkoSerhiy** [comment]
Hey @Startrekzky ,

Thank you for your feedback! I implemented the points 1 and 3 you mentioned.

There are no raw files, as you can actually edit the `.png` images themselves using `Drawio`, be it an extension of your IDE, web, or desktop application (`Drawio` puts its metadata directly into the exported `.png`). 🤯 

A quick side note: I see there are a lot of images inside the same folder, which makes it easy to lose the image you put inside among the others. I think it will help if we structure them the same way as the docs. I'd put that into a discussion channel so we all get on the same page either way. What do you think?

**Comment by Startrekzky** [comment]
"A quick side note: I see there are a lot of images inside the same folder, which makes it easy to lose the image you put inside among the others."

Hi @KucherenkoSerhiy , thanks for the suggestion. The reason for this is that it's hard to migrate the static/images to every version, so we only add the new images to the right versions and will not touch the old images unless we're going to modify them in the future.

**Review by Startrekzky — APPROVED** [review]
LGTM

**Pull request merged**
