### PR TITLE
Added GitHub Issue Tracker for docs link on footer

### LINKED ISSUE #370: [Doc][incubator-devlake-website] GitHub Issue Tracker for this Docs repo is missing on the Website's footer
## Documentation Scope
The scope is for all pages of the website (footer).

## Describe the Change
As we already have the link which redirects us to GitHub Issues but that is just for the incubator-devlake repo, and not for incubator-devlake-website repo.
Adding this link will be useful for all those who want to contribute to docs.

## Screenshots
- Screenshot of the current website:
before_apache

- Screenshot of what I want to add:
after_apache

### PR DESCRIPTION
**Pull request by aparna2071**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have `npm run build` and `npm run serve` locally before submitting this PR
- [x] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation

# Summary

### Does this close any open issues?
Closes #370

### Screenshots
I have tried to run it on local & it worked as expected.
after_apache

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Review by yumengwang03 — APPROVED** [review]
LGTM

**Comment by Xin1Guan** [comment]
Thank you for your contribution. Please join our slack: https://join.slack.com/t/devlake-io/shared_invite/zt-1igtblgaf-szBSdpVNXFehQRVcGH3Ifg and @XinGuan or join our wechat group and @关鑫, we want to issue you a certificate to honor your contribution.

**Comment by aparna2071** [comment]
Hi, thank you so much for inviting me 😄 but the link is not working. Attaching screenshot, please look into this.


Screenshot_2023-01-09-13-03-22-50_abb9c8060a0a12c5ac89e934e52a2f4f

**Comment by Xin1Guan** [comment]
Sorry, the previous link address is out of date, this is a new one: https://join.slack.com/t/devlake-io/shared_invite/zt-1mrobitzq-_4hhjq84GNwOPdRkH8zbsA

**Comment by aparna2071** [comment]
Thanks for the updated link, I have joined the group 👍 
Looking forward to more collaborations 🤝

**Pull request merged**
