### PR TITLE
docs: fix broken link style

### PR DESCRIPTION
**Pull request by tisonkun**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have `npm run build` and `npm run serve` locally before submitting this PR
- [x] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation

# Summary

### Does this close any open issues?
Closes xx

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by tisonkun** [comment]
```
✗ [429] https://i.imgur.com/onxGG8d.png | Failed: Network error: Too Many Requests
✗ [429] https://i.imgur.com/zaExAUG.png | Failed: Network error: Too Many Requests
✗ [429] https://i.imgur.com/N7E9Vwd.png | Failed: Network error: Too Many Requests
✗ [429] https://i.imgur.com/BpZY8dN.png | Failed: Network error: Too Many Requests
↻ [[42](https://github.com/apache/incubator-devlake-website/actions/runs/4980567969/jobs/8913644780#step:9:43)9] https://i.imgur.com/N7E9Vwd.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/onxGG8d.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/BpZY8dN.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/zaExAUG.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/BpZY8dN.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/onxGG8d.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/N7E9Vwd.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/zaExAUG.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/zaExAUG.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/BpZY8dN.png | Cached: Error (cached)
↻ [429] https://i.imgur.com/N7E9Vwd.png | Cached: Error (cached)
```

Unrelated errors.

**Review by mindlesscloud — APPROVED** [review]
LGTM

**Comment by klesh** [comment]
@tisonkun Thanks for your contribution, would you mind rebasing the PR so it can be merged.

**Comment by tisonkun** [comment]
Updated. You can use "squash and merge" to squash the merge commit.

**Comment by ghost** [comment]
Hi @tisonkun 
Thank you for your contribution!

I’m Joshua Poddoku, Lead Evangelist for Apache DevLake.

We would want to issue you a certificate to honor your contribution on behalf of Apache DevLake and feature you on [contributors page](https://devlake.apache.org/team).

Please join our slack for further communication: https://join.slack.com/t/devlake-io/shared_invite/zt-18uayb6ut-cHOjiYcBwERQ8VVPZ9cQQw

Kindly acknowledge! Thanks again

**Pull request merged**
