### PR TITLE
docs: update Development Workflow page link

### LINKED ISSUE #574: [Doc][ReadMe] Development Workflow page link is incorrect
Screenshot 2023-07-06 at 4 09 22 AM

Correct Link: https://github.com/apache/incubator-devlake-website/blob/main/community/MakingContributions/development-workflow.md

### PR DESCRIPTION
**Pull request by anjy7**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [✅] I have `npm run build` and `npm run serve` locally before submitting this PR
- [✅] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation

# Summary

### Does this close any open issues?
Closes #574

### Screenshots
Include any relevant screenshots here.

### Other Information
Corrected the Development Workflow page link in README.md

### CODE REVIEW

**Review by Startrekzky — APPROVED** [review]
LGTM

**Comment by anjy7** [comment]
Hi @Startrekzky , could you please merge it

**Comment by klesh** [comment]
@anjy7 Hi, PR can be merged only after all checks are completed successfully. However, it somehow stuck 😂
image

**Comment by klesh** [comment]
@anjy7 Can you try updating the PR and see if it fixes the problem?

Maybe you can use the following trick to renew the commit sha without actually modifying anything:
```sh
git commit --amend
// text editor would pop out, please save and close without changing anything
git push -f
```

**Comment by anjy7** [comment]
Done @klesh

**Pull request merged**
