### PR TITLE
update the developer manuals doc

### PR DESCRIPTION
**Pull request by gzwine**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have `npm run build` and `npm run serve` locally before submitting this PR
- [x] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation

# Summary

### Does this close any open issues?
None

### Screenshots
Include any relevant screenshots here.
None

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

**Comment by Startrekzky** [comment]
Are there any differences after adding `.git` at the end of the URL?

**Comment by gzwine** [comment]
> Are there any differences after adding `.git` at the end of the URL?

the different is very small
https://segmentfault.com/q/1010000015373637
https://stackoverflow.com/questions/11068576/why-do-some-repository-urls-end-in-git-while-others-dont

but other similar places in the project have `.git`, so I think it should be consistent.

**Review by mindlesscloud — APPROVED** [review]
LGTM

**Comment by Xin1Guan** [comment]
Thank you for your contribution. Please join our slack: https://join.slack.com/t/devlake-io/shared_invite/zt-1mrobitzq-_4hhjq84GNwOPdRkH8zbsA and @ Xin Guan or join our wechat group and @关鑫, we want to issue you a certificate to honor your contribution.

**Pull request merged**
