### PR TITLE
docs: Playground Blog

### PR DESCRIPTION
**Pull request by lenntt**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [X] I have `npm run build` and `npm run serve` locally before submitting this PR
- [X] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation

# Summary

### Does this close any open issues?
No, 
the context of the blogpost is https://github.com/apache/incubator-devlake-playground
with the suggestion by @d4x1 to write a blog https://github.com/apache/incubator-devlake/pull/6963#issuecomment-1972997426

### CODE REVIEW

**Comment by d4x1** [comment]
Is this image(static/img/Blog/DevLake-Playground-How-to-explore-your-data.png) generated by AI? :)

**Comment by lenntt** [comment]
> Is this image(static/img/Blog/DevLake-Playground-How-to-explore-your-data.png) generated by AI? :)

yes, dall-e 3. is it not in policy?

**Comment by lenntt** [comment]
Any suggestions or rework we should take care of?

**Review by d4x1 — APPROVED** [review]

**Comment by d4x1** [comment]
> Any suggestions or rework we should take care of?

Great work! I have forgotten to merge it. sorry!

**Comment by lenntt** [comment]
> > Any suggestions or rework we should take care of?
> 
> Great work! I have forgotten to merge it. sorry!

No worries. Many thanks!

**Pull request merged**
