### PR TITLE
Fix:Homepage Header

### PR DESCRIPTION
**Pull request by dheerajsingh89**
### ⚠️ &nbsp;&nbsp;Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have `npm run build` and `npm run serve` locally before submitting this PR
- [x] I have read through the [Contributing](https://devlake.apache.org/community/) Documentation

# Summary

### Does this close any open issues?
Closes Issue : [#705 ]

### Screenshots
Include any relevant screenshots here.

### Other Information
Updated the anchor tags of the companies icons so that after clicking the icons , we can redirect to company page on new tab instead of same tab in order to maintain better user experience

### CODE REVIEW

**Review by mintsweet — APPROVED** [review]
LGTM.

**Comment by ghost** [comment]
Hi @itsdheerajdp,

Thank you for your contribution! I'm Joshua Poddoku, Committer at Apache DevLake. We'd love for you to join our Slack community or DM me incase you've joined already: https://join.slack.com/t/devlake-io/shared_invite/zt-18uayb6ut-cHOjiYcBwERQ8VVPZ9cQQw. Could you please share your full name there? We want to recognize your efforts with a certificate of contribution.

Best,
Joshua

**Comment by dheerajsingh89** [comment]
> Hi @itsdheerajdp,
> 
> Thank you for your contribution! I'm Joshua Poddoku, Committer at Apache DevLake. We'd love for you to join our Slack community or DM me incase you've joined already: https://join.slack.com/t/devlake-io/shared_invite/zt-18uayb6ut-cHOjiYcBwERQ8VVPZ9cQQw. Could you please share your full name there? We want to recognize your efforts with a certificate of contribution.
> 
> Best, Joshua

I am trying to use this link to join slack but it's not working ..?

**Comment by klesh** [comment]
Weird, the link works for me.

**Comment by dheerajsingh89** [comment]
> Weird, the link works for me.

I send the DM to @JoshuaPoddoku in Slack

**Pull request merged**
