### PR TITLE
added live demo page in nav bar

### PR DESCRIPTION
**Pull request by Bivas-Biswas**
## Build a new live demo page for the website

issue: #240 

After change:
image

### CODE REVIEW

**Comment by klesh** [comment]
@Startrekzky @yumengwang03 Please take a look at the PR, thanks

**Comment by yumengwang03** [comment]
This is awesome! Thank you for working on this feature. There's a little problem that needs to be fixed before merging this PR, as shown in the screenshot below.

Screen Shot 2022-10-17 at 5 35 03 PM

**Review by Startrekzky — APPROVED** [review]
LGTM

**Comment by yumengwang03** [comment]
@Bivas-Biswas We‘ve merged this first, because we need to freeze our v0.14 docs :) I've created another issue to address the remaining problem here https://github.com/apache/incubator-devlake-website/issues/271. You are more than welcome to work on it. We appreciate your contribution!

**Pull request merged**
